### ISSUE TITLE
Add Raw Request Option

### ISSUE THREAD

**Issue by ZeyoYT** [masecla22/Reddit4J#19]
**Is your feature request related to a problem? Please describe.**
Some Endpoints are not Supported, like the random endpoint, and it would have been great if there was a option to get raw json response for endpoints that are not covered or in general for all

**Describe the solution you'd like**
A Method to get Raw Json Response

**Describe alternatives you've considered**
For now i have not considered anything for this

**Additional context**
To be honest, i just wanted the oauth authentication, since reddit made non-oauth endpoints blocked, i am having trouble in authenticating the api for my use case, i just want to fetch random post or sometimes new or hot posts from reddit

**Comment by masecla22** [comment]
I'll look into implementing something like this, but I don't have a lot of time. 

I'll leave this open, and if someone wants to pick it up, they're free to do so!

**Comment by DisruptionSystemsINC** [comment]
On it

**Comment by DisruptionSystemsINC** [comment]
The /random endpoint has pretty weird behaviour. 
It returns 403 Forbidden when you are authorized, but when leaving out the Auth header, it works just fine

**Comment by ZeyoYT** [comment]
Weird, well after this because i had to find a solution to my problem, i manage to fix my authentication problem i was getting, for me the authorised endpoint for random is working but the unauthorised one will throw 403

**Comment by DisruptionSystemsINC** [comment]
> Weird, well after this because i had to find a solution to my problem, i manage to fix my authentication problem i was getting, for me the authorised endpoint for random is working but the unauthorised one will throw 403

What type of app are you using? 
Currently i am testing with user script

**Comment by ZeyoYT** [comment]
> > Weird, well after this because i had to find a solution to my problem, i manage to fix my authentication problem i was getting, for me the authorised endpoint for random is working but the unauthorised one will throw 403
> 
> What type of app are you using? 
> Currently i am testing with user script
> 

I develop discord bots, i was going to use this for fetching memes and random posts, but due to the unavailability i had to implement a custom solution for this, basically using the raw reddit api without any wrappers

**Comment by masecla22** [comment]
This has been fixed in #20
